### PR TITLE
Pp 42 create mui theme provider and create all properties for future fillings

### PR DESCRIPTION
**Pull request by AnnaPestova1**
Added theme provider for app MUI setup. 
We should use color path according the screenshot.
image

### CODE REVIEW

**Review by wowgr8 — CHANGES_REQUESTED** [review]
@AnnaPestova1 ,  I pulled the feature branch down and ran `npm install`, I also solved the merge conflicts locally in package-lock.json and package.json but I'm still getting these 3 following errors:

Errors 1, 2:
image


Error 3:
image

**Comment by AnnaPestova1** [comment]
> @AnnaPestova1 , I pulled the feature branch down and ran `npm install`, I also solved the merge conflicts locally in package-lock.json and package.json but I'm still getting these 3 following errors:
> 
> Errors 1, 2: image
> 
> Error 3: image

Done

**Review by wowgr8 — APPROVED** [review]
Nice job, looks great!

**Review by MunirNuristani — APPROVED** [review]
LGTM! Great work.

**Pull request merged**
