### PR TITLE
PP 6 - Routes and Pages from schema

### PR DESCRIPTION
**Pull request by wowgr8**
Added static version of our application. Created Routes, Dynamic Routes, and Pages for each component in our schema:

image

### CODE REVIEW

**Comment by ElenaCherpakova** [comment]
@wowgr8 , the navbar and footer should remain in the components folder, but the component folder should be on the same level as the app folder not inside the app

**Review by ElenaCherpakova — COMMENTED** [review]
the navbar and footer should remain in the components folder, but the component folder should be on the same level as the app folder not inside the app

**Review by ElenaCherpakova — CHANGES_REQUESTED** [review]
the navbar and footer should remain in the components folder, but the component folder should be on the same level as the app folder not inside the app

**Comment by AnnaPestova1** [comment]
> the navbar and footer should remain in the components folder, but the component folder should be on the same level as the app folder not inside the app

The documentation for reference: https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts  and main part from the documentation is 
image

**Comment by wowgr8** [comment]
Thanks @ElenaCherpakova , I made those changes and moved the components out in scope.

**Comment by wowgr8** [comment]
> the navbar and footer should remain in the components folder, but the component folder should be on the same level as the app folder not inside the app

Thanks @ElenaCherpakova , I made those changes and moved the components out in scope.

**Review by AnnaPestova1 — APPROVED** [review]
this issue isn't critical, but could you check that we have this route also? 
image

**Comment by wowgr8** [comment]
> this issue isn't critical, but could you check that we have this route also? image

Whoops. Done!

**Review by MunirNuristani — APPROVED** [review]
LGTM! Great work. Just remember, You will need many more files than you anticipate. From my POV, agreeing on where you will put the component files is better. Would you want a component file within each page or gather all components ( related to all pages) into a larger component folder? Otherwise, this is all great

**Review by ElenaCherpakova — APPROVED** [review]

**Pull request merged**
