### PR TITLE
create models, install jwt bycrypt and add mongo sanitization

### PR DESCRIPTION
**Pull request by ElenaCherpakova**
1. Created models folder with models for buyers, sellers, cards, users, market data, order history, and seller listings.
2. Installed JWT and bcrypt for authentication.
3. Integrated mongo-sanitization for enhanced security.
4. Created a folder named 'API' and added users to it. Also added a route file inside the folder.

### CODE REVIEW

**Comment by ElenaCherpakova** [comment]
found a typed error

**Review by AnnaSolovykh — APPROVED** [review]
Looks good to me!

**Review by AnnaPestova1 — APPROVED** [review]
looks good to me

**Review by MunirNuristani — COMMENTED** [review]
All looks good. Great work.

**Pull request merged**
