### PR TITLE
Pp 11 create card component

### PR DESCRIPTION
**Pull request by LiubovCass**
Created Card Component. Button color "secondary"

### CODE REVIEW

**Review by AnnaPestova1 — CHANGES_REQUESTED** [review]
Hi Luba! I love your Card component! Could you please implement imitation of card object to display a mock data (that we will receive from Backend later) and send it to the Card component via props? The Card model is here https://github.com/Code-the-Dream-School/ffprac-team6/blob/dev-main/models/Card.js

**Comment by LiubovCass** [comment]
Created new commit with some changes according to your suggestions and card model

**Review by AnnaPestova1 — APPROVED** [review]
Great! switch navigation logic from <Link> to onClick and solve merge conflict before merge this pull request

**Review by MunirNuristani — APPROVED** [review]
LGTM, but you have to pull dev and resolve conflict before merging.

**Pull request merged**
