### PR TITLE
Pp 33 create cards page

### PR DESCRIPTION
**Pull request by LiubovCass**
layout market page

### CODE REVIEW

**Review by AnnaPestova1 — CHANGES_REQUESTED** [review]
Hi Luba! 
Great page!

Could you please remove MuiButton text from <Button> from your CardComponent
image
this text give us the error in the console 
image

And could you please clean your code from commented lines?

**Review by MunirNuristani — DISMISSED** [review]
Can you merge dev and resolve conflicts

**Review by AnnaPestova1 — COMMENTED** [review]
Hi! Looks nice! we have some issues: 
we do not need this anymore: 
image
image


and also when I click on card, it opens route for backend 
image
 not the page for single card

**Comment by LiubovCass** [comment]
Thank you, Anna. Code was refactored according to your suggestions

**Review by AnnaSolovykh — APPROVED** [review]

**Review by AnnaPestova1 — APPROVED** [review]

**Pull request merged**
