### PR TITLE
added prettier file

### PR DESCRIPTION
**Pull request by AnnaPestova1**
Added prettier configurations. Here the instruction how to setup prettier https://docs.google.com/document/d/1VFMsl1FH3wm20yIAF-yl55rGnaK9gqENHvq5HM39Fpc/edit?usp=sharing

### CODE REVIEW

**Review by AnnaSolovykh — APPROVED** [review]
Looks good to me!

**Review by wowgr8 — APPROVED** [review]
Looks good!

**Review by Victoria240 — COMMENTED** [review]
Happy with this!

**Comment by ofeterovskaya** [comment]
great

**Pull request merged**
