### PR TITLE
Pp 31 create footer

### PR DESCRIPTION
**Pull request by LiubovCass**
Created Footer component with Copyright and list of links. theme colors used

### CODE REVIEW

**Review by AnnaPestova1 — CHANGES_REQUESTED** [review]
Hi Luba! Great job! Just couple small issues.:
1. In our dev-main branch all css files that comes with next.js are commented. Can you do the same in your code? (it will help you to get rid of dark theme for now)
2. You are treating Link component from Next.js as a MUI component. Thats why you cannot change the link's text color. Use buttons or add stiles for a:link in css file.

**Review by AnnaPestova1 — APPROVED** [review]
great!

**Review by Victoria240 — COMMENTED** [review]
This looks great, Luba! Well-done 
I've only got one concern. When I created the navbar, I merged the 'About' and 'Our Team' together. Do they have to be separate? If yes, I can make changes to the navbar component. 
@AnnaPestova1 What do you think?

**Review by AnnaSolovykh — APPROVED** [review]

**Comment by LiubovCass** [comment]
Thank you @Victoria240. I changed link "about" for link "policies"

**Pull request merged**
